### ISSUE TITLE
Unclear error message about id.vars

### ISSUE THREAD

**Issue by BlackEdder** [libbi/RBi#12]
Currently I see the following error message, but it is unclear to me where/how to provide id.vars and measure.vars. I couldn't find anything about them in the help (I guess it has something to do with the coord_dims and the time_dim?)

```
To be consistent with reshape2's melt, id.vars and measure.vars are internally guessed when both are 'NULL'. All non-numeric/integer/logical type columns are conisdered id.vars, which in this case are columns []. Consider providing at least one of 'id' or 'measure' vars in future.
```

Also note that the error message actually doesn't show any columns. And spelling mistake in conisdered.

**Comment by sbfnk** [comment]
Can you give a reproducible example? The spelling mistake is data.table's.

**Comment by BlackEdder** [comment]
Emailed an example with data files to you. The error does not appear when running the model with `bi_generate_dataset`, only when trying to sample, so it seems to be somewhere in the observed part.
