### ISSUE TITLE
bi_read throws error when calling sample with thinning enabled

### ISSUE THREAD

**Issue by BlackEdder** [libbi/RBi#9]
If I call the `sample` function with `thin = 10` (or another value) I get the following error when trying to read the resulting object:

```R
bi_read(bi)
Error in factor(mav[[col]], labels = dims[[col]]) : 
  invalid 'labels'; length 10 should be 1 or 100
```

**Comment by sbfnk** [comment]
Thanks @BlackEdder. I can't reproduce this. Can you provide a minimal reproducible example?

**Comment by BlackEdder** [comment]
I've emailed you the R object (bi) that resulted in the error
